//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/tball/tmp/j2objc-0.8.6.1/junit/build_result/java/org/junit/internal/builders/AllDefaultPossibilitiesBuilder.java
//
//  Created by tball on 9/18/13.
//

#ifndef _OrgJunitInternalBuildersAllDefaultPossibilitiesBuilder_H_
#define _OrgJunitInternalBuildersAllDefaultPossibilitiesBuilder_H_

@class IOSClass;
@class OrgJunitInternalBuildersAnnotatedBuilder;
@class OrgJunitInternalBuildersIgnoredBuilder;
@class OrgJunitInternalBuildersJUnit3Builder;
@class OrgJunitInternalBuildersJUnit4Builder;
@class OrgJunitRunnerRunner;

#import "JreEmulation.h"
#include "org/junit/runners/model/RunnerBuilder.h"

@interface OrgJunitInternalBuildersAllDefaultPossibilitiesBuilder : OrgJunitRunnersModelRunnerBuilder {
 @public
  BOOL fCanUseSuiteMethod_;
}

- (id)initWithBoolean:(BOOL)canUseSuiteMethod;
- (OrgJunitRunnerRunner *)runnerForClassWithIOSClass:(IOSClass *)testClass;
- (OrgJunitInternalBuildersJUnit4Builder *)junit4Builder;
- (OrgJunitInternalBuildersJUnit3Builder *)junit3Builder;
- (OrgJunitInternalBuildersAnnotatedBuilder *)annotatedBuilder;
- (OrgJunitInternalBuildersIgnoredBuilder *)ignoredBuilder;
- (OrgJunitRunnersModelRunnerBuilder *)suiteMethodBuilder;
- (void)copyAllFieldsTo:(OrgJunitInternalBuildersAllDefaultPossibilitiesBuilder *)other;
@end

#endif // _OrgJunitInternalBuildersAllDefaultPossibilitiesBuilder_H_
