//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/tball/tmp/j2objc-0.8.6.1/junit/build_result/java/org/junit/internal/builders/JUnit3Builder.java
//
//  Created by tball on 9/18/13.
//

#ifndef _OrgJunitInternalBuildersJUnit3Builder_H_
#define _OrgJunitInternalBuildersJUnit3Builder_H_

@class IOSClass;
@class OrgJunitRunnerRunner;

#import "JreEmulation.h"
#include "org/junit/runners/model/RunnerBuilder.h"

@interface OrgJunitInternalBuildersJUnit3Builder : OrgJunitRunnersModelRunnerBuilder {
}

- (OrgJunitRunnerRunner *)runnerForClassWithIOSClass:(IOSClass *)testClass;
- (BOOL)isPre4TestWithIOSClass:(IOSClass *)testClass;
- (id)init;
@end

#endif // _OrgJunitInternalBuildersJUnit3Builder_H_
