//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/tball/tmp/j2objc-0.8.6.1/junit/build_result/java/org/junit/internal/builders/NullBuilder.java
//
//  Created by tball on 9/18/13.
//

#ifndef _OrgJunitInternalBuildersNullBuilder_H_
#define _OrgJunitInternalBuildersNullBuilder_H_

@class IOSClass;
@class OrgJunitRunnerRunner;

#import "JreEmulation.h"
#include "org/junit/runners/model/RunnerBuilder.h"

@interface OrgJunitInternalBuildersNullBuilder : OrgJunitRunnersModelRunnerBuilder {
}

- (OrgJunitRunnerRunner *)runnerForClassWithIOSClass:(IOSClass *)each;
- (id)init;
@end

#endif // _OrgJunitInternalBuildersNullBuilder_H_
