//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/tball/tmp/j2objc-0.8.6.1/junit/build_result/java/org/junit/internal/builders/SuiteMethodBuilder.java
//
//  Created by tball on 9/18/13.
//

#ifndef _OrgJunitInternalBuildersSuiteMethodBuilder_H_
#define _OrgJunitInternalBuildersSuiteMethodBuilder_H_

@class IOSClass;
@class OrgJunitRunnerRunner;

#import "JreEmulation.h"
#include "org/junit/runners/model/RunnerBuilder.h"

@interface OrgJunitInternalBuildersSuiteMethodBuilder : OrgJunitRunnersModelRunnerBuilder {
}

- (OrgJunitRunnerRunner *)runnerForClassWithIOSClass:(IOSClass *)each;
- (BOOL)hasSuiteMethodWithIOSClass:(IOSClass *)testClass;
- (id)init;
@end

#endif // _OrgJunitInternalBuildersSuiteMethodBuilder_H_
