//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/firebase/client/Query.java
//
//  Created by dthurn on 11/1/13.
//

#include "../../../com/firebase/client/Query.h"
#include "java/io/PrintStream.h"
#include "java/lang/System.h"

@implementation FCQuery

- (id)initWithId:(id)firebase {
  if (self = [super init]) {
    self->firebase_ = firebase;
  }
  return self;
}

- (void)helloWorld {
  [((JavaIoPrintStream *) nil_chk([JavaLangSystem out])) printlnWithNSString:@"Hello, world!"];
}

- (void)copyAllFieldsTo:(FCQuery *)other {
  [super copyAllFieldsTo:other];
  other->firebase_ = firebase_;
}

@end
