//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/tball/tmp/j2objc-0.8.6.1/junit/build_result/java/org/junit/internal/runners/statements/ExpectException.java
//
//  Created by tball on 9/18/13.
//

#ifndef _OrgJunitInternalRunnersStatementsExpectException_H_
#define _OrgJunitInternalRunnersStatementsExpectException_H_

@class IOSClass;

#import "JreEmulation.h"
#include "org/junit/runners/model/Statement.h"

@interface OrgJunitInternalRunnersStatementsExpectException : OrgJunitRunnersModelStatement {
 @public
  OrgJunitRunnersModelStatement *fNext_;
  IOSClass *fExpected_;
}

- (id)initWithOrgJunitRunnersModelStatement:(OrgJunitRunnersModelStatement *)next
                               withIOSClass:(IOSClass *)expected;
- (void)evaluate;
- (void)copyAllFieldsTo:(OrgJunitInternalRunnersStatementsExpectException *)other;
@end

J2OBJC_FIELD_SETTER(OrgJunitInternalRunnersStatementsExpectException, fNext_, OrgJunitRunnersModelStatement *)
J2OBJC_FIELD_SETTER(OrgJunitInternalRunnersStatementsExpectException, fExpected_, IOSClass *)

#endif // _OrgJunitInternalRunnersStatementsExpectException_H_
