//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/tball/tmp/j2objc-0.8.6.1/junit/build_result/java/org/junit/internal/runners/statements/Fail.java
//
//  Created by tball on 9/18/13.
//

#ifndef _OrgJunitInternalRunnersStatementsFail_H_
#define _OrgJunitInternalRunnersStatementsFail_H_

@class JavaLangThrowable;

#import "JreEmulation.h"
#include "org/junit/runners/model/Statement.h"

@interface OrgJunitInternalRunnersStatementsFail : OrgJunitRunnersModelStatement {
 @public
  JavaLangThrowable *fError_;
}

- (id)initWithJavaLangThrowable:(JavaLangThrowable *)e;
- (void)evaluate;
- (void)copyAllFieldsTo:(OrgJunitInternalRunnersStatementsFail *)other;
@end

J2OBJC_FIELD_SETTER(OrgJunitInternalRunnersStatementsFail, fError_, JavaLangThrowable *)

#endif // _OrgJunitInternalRunnersStatementsFail_H_
