//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/tball/tmp/j2objc-0.8.6.1/junit/build_result/java/org/junit/internal/runners/statements/InvokeMethod.java
//
//  Created by tball on 9/18/13.
//

#ifndef _OrgJunitInternalRunnersStatementsInvokeMethod_H_
#define _OrgJunitInternalRunnersStatementsInvokeMethod_H_

@class OrgJunitRunnersModelFrameworkMethod;

#import "JreEmulation.h"
#include "org/junit/runners/model/Statement.h"

@interface OrgJunitInternalRunnersStatementsInvokeMethod : OrgJunitRunnersModelStatement {
 @public
  OrgJunitRunnersModelFrameworkMethod *fTestMethod_;
  id fTarget_;
}

- (id)initWithOrgJunitRunnersModelFrameworkMethod:(OrgJunitRunnersModelFrameworkMethod *)testMethod
                                           withId:(id)target;
- (void)evaluate;
- (void)copyAllFieldsTo:(OrgJunitInternalRunnersStatementsInvokeMethod *)other;
@end

J2OBJC_FIELD_SETTER(OrgJunitInternalRunnersStatementsInvokeMethod, fTestMethod_, OrgJunitRunnersModelFrameworkMethod *)
J2OBJC_FIELD_SETTER(OrgJunitInternalRunnersStatementsInvokeMethod, fTarget_, id)

#endif // _OrgJunitInternalRunnersStatementsInvokeMethod_H_
