//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/tball/tmp/j2objc-0.8.6.1/junit/build_result/java/org/junit/internal/runners/statements/RunAfters.java
//
//  Created by tball on 9/18/13.
//

#ifndef _OrgJunitInternalRunnersStatementsRunAfters_H_
#define _OrgJunitInternalRunnersStatementsRunAfters_H_

@protocol JavaUtilList;

#import "JreEmulation.h"
#include "org/junit/runners/model/Statement.h"

@interface OrgJunitInternalRunnersStatementsRunAfters : OrgJunitRunnersModelStatement {
 @public
  OrgJunitRunnersModelStatement *fNext_;
  id fTarget_;
  id<JavaUtilList> fAfters_;
}

- (id)initWithOrgJunitRunnersModelStatement:(OrgJunitRunnersModelStatement *)next
                           withJavaUtilList:(id<JavaUtilList>)afters
                                     withId:(id)target;
- (void)evaluate;
- (void)copyAllFieldsTo:(OrgJunitInternalRunnersStatementsRunAfters *)other;
@end

J2OBJC_FIELD_SETTER(OrgJunitInternalRunnersStatementsRunAfters, fNext_, OrgJunitRunnersModelStatement *)
J2OBJC_FIELD_SETTER(OrgJunitInternalRunnersStatementsRunAfters, fTarget_, id)
J2OBJC_FIELD_SETTER(OrgJunitInternalRunnersStatementsRunAfters, fAfters_, id<JavaUtilList>)

#endif // _OrgJunitInternalRunnersStatementsRunAfters_H_
