//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/tball/tmp/j2objc-0.8.6.1/junit/build_result/java/org/junit/internal/runners/statements/RunBefores.java
//
//  Created by tball on 9/18/13.
//

#ifndef _OrgJunitInternalRunnersStatementsRunBefores_H_
#define _OrgJunitInternalRunnersStatementsRunBefores_H_

@protocol JavaUtilList;

#import "JreEmulation.h"
#include "org/junit/runners/model/Statement.h"

@interface OrgJunitInternalRunnersStatementsRunBefores : OrgJunitRunnersModelStatement {
 @public
  OrgJunitRunnersModelStatement *fNext_;
  id fTarget_;
  id<JavaUtilList> fBefores_;
}

- (id)initWithOrgJunitRunnersModelStatement:(OrgJunitRunnersModelStatement *)next
                           withJavaUtilList:(id<JavaUtilList>)befores
                                     withId:(id)target;
- (void)evaluate;
- (void)copyAllFieldsTo:(OrgJunitInternalRunnersStatementsRunBefores *)other;
@end

J2OBJC_FIELD_SETTER(OrgJunitInternalRunnersStatementsRunBefores, fNext_, OrgJunitRunnersModelStatement *)
J2OBJC_FIELD_SETTER(OrgJunitInternalRunnersStatementsRunBefores, fTarget_, id)
J2OBJC_FIELD_SETTER(OrgJunitInternalRunnersStatementsRunBefores, fBefores_, id<JavaUtilList>)

#endif // _OrgJunitInternalRunnersStatementsRunBefores_H_
