//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: Classes/java/util/concurrent/TimeUnit.java
//
//  Created by tball on 9/18/13.
//

#ifndef _JavaUtilConcurrentTimeUnit_H_
#define _JavaUtilConcurrentTimeUnit_H_

#import "JreEmulation.h"
#include "java/lang/Enum.h"

typedef enum {
  JavaUtilConcurrentTimeUnit_DAYS = 0,
  JavaUtilConcurrentTimeUnit_HOURS = 1,
  JavaUtilConcurrentTimeUnit_MINUTES = 2,
  JavaUtilConcurrentTimeUnit_SECONDS = 3,
  JavaUtilConcurrentTimeUnit_MILLISECONDS = 4,
  JavaUtilConcurrentTimeUnit_MICROSECONDS = 5,
  JavaUtilConcurrentTimeUnit_NANOSECONDS = 6,
} JavaUtilConcurrentTimeUnit;

@interface JavaUtilConcurrentTimeUnitEnum : JavaLangEnum < NSCopying > {
 @public
  long long int value_;
}
+ (JavaUtilConcurrentTimeUnitEnum *)DAYS;
+ (JavaUtilConcurrentTimeUnitEnum *)HOURS;
+ (JavaUtilConcurrentTimeUnitEnum *)MINUTES;
+ (JavaUtilConcurrentTimeUnitEnum *)SECONDS;
+ (JavaUtilConcurrentTimeUnitEnum *)MILLISECONDS;
+ (JavaUtilConcurrentTimeUnitEnum *)MICROSECONDS;
+ (JavaUtilConcurrentTimeUnitEnum *)NANOSECONDS;
+ (IOSObjectArray *)values;
+ (JavaUtilConcurrentTimeUnitEnum *)valueOfWithNSString:(NSString *)name;
- (id)copyWithZone:(NSZone *)zone;
- (id)initWithLong:(long long int)value
      withNSString:(NSString *)__name
           withInt:(int)__ordinal;
- (long long int)convertWithLong:(long long int)sourceDuration
withJavaUtilConcurrentTimeUnitEnum:(JavaUtilConcurrentTimeUnitEnum *)unit;
- (long long int)toDaysWithLong:(long long int)duration;
- (long long int)toHoursWithLong:(long long int)duration;
- (long long int)toMinutesWithLong:(long long int)duration;
- (long long int)toSecondsWithLong:(long long int)duration;
- (long long int)toMillisWithLong:(long long int)duration;
- (long long int)toMicrosWithLong:(long long int)duration;
- (long long int)toNanosWithLong:(long long int)duration;
- (long long int)convertWithLong:(long long int)sourceDurationNs;
@end

#endif // _JavaUtilConcurrentTimeUnit_H_
