//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/tball/tmp/j2objc-0.8.6.1/junit/build_result/java/org/junit/runner/manipulation/Filterable.java
//
//  Created by tball on 9/18/13.
//

#ifndef _OrgJunitRunnerManipulationFilterable_H_
#define _OrgJunitRunnerManipulationFilterable_H_

@class OrgJunitRunnerManipulationFilter;

#import "JreEmulation.h"

@protocol OrgJunitRunnerManipulationFilterable < NSObject, JavaObject >
- (void)filterWithOrgJunitRunnerManipulationFilter:(OrgJunitRunnerManipulationFilter *)filter;
@end

#endif // _OrgJunitRunnerManipulationFilterable_H_
