//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/tball/tmp/j2objc-0.8.6.1/junit/build_result/java/org/junit/runner/manipulation/NoTestsRemainException.java
//
//  Created by tball on 9/18/13.
//

#ifndef _OrgJunitRunnerManipulationNoTestsRemainException_H_
#define _OrgJunitRunnerManipulationNoTestsRemainException_H_

#import "JreEmulation.h"
#include "java/lang/Exception.h"

#define OrgJunitRunnerManipulationNoTestsRemainException_serialVersionUID 1

@interface OrgJunitRunnerManipulationNoTestsRemainException : JavaLangException {
}

- (id)init;
@end

#endif // _OrgJunitRunnerManipulationNoTestsRemainException_H_
