//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: apache_harmony/classlib/modules/luni/src/main/java/java/io/PrintStream.java
//
//  Created by tball on 9/18/13.
//

#ifndef _JavaIoPrintStream_H_
#define _JavaIoPrintStream_H_

@class IOSByteArray;
@class IOSCharArray;
@class JavaIoFile;
@class JavaIoOutputStream;
@protocol JavaLangCharSequence;

#import "JreEmulation.h"
#include "java/io/Closeable.h"
#include "java/io/FilterOutputStream.h"
#include "java/lang/Appendable.h"

@interface JavaIoPrintStream : JavaIoFilterOutputStream < JavaLangAppendable, JavaIoCloseable > {
 @public
  BOOL ioError_;
  BOOL autoflush_;
  NSString *encoding_;
  NSString *lineSeparator_;
}

+ (NSString *)TOKEN_NULL;
- (id)initWithJavaIoOutputStream:(JavaIoOutputStream *)outArg;
- (id)initWithJavaIoOutputStream:(JavaIoOutputStream *)outArg
                     withBoolean:(BOOL)autoflush;
- (id)initWithJavaIoOutputStream:(JavaIoOutputStream *)outArg
                     withBoolean:(BOOL)autoflush
                    withNSString:(NSString *)enc;
- (id)initWithJavaIoFile:(JavaIoFile *)file;
- (id)initWithJavaIoFile:(JavaIoFile *)file
            withNSString:(NSString *)csn;
- (id)initWithNSString:(NSString *)fileName;
- (id)initWithNSString:(NSString *)fileName
          withNSString:(NSString *)csn;
- (BOOL)checkError;
- (void)close;
- (void)flush;
- (void)newline OBJC_METHOD_FAMILY_NONE;
- (void)printWithCharArray:(IOSCharArray *)charArray;
- (void)printWithChar:(unichar)ch;
- (void)printWithDouble:(double)dnum;
- (void)printWithFloat:(float)fnum;
- (void)printWithInt:(int)inum;
- (void)printWithLong:(long long int)lnum;
- (void)printWithId:(id)obj;
- (void)printWithNSString:(NSString *)str;
- (void)printWithBoolean:(BOOL)bool_;
- (void)println;
- (void)printlnWithCharArray:(IOSCharArray *)charArray;
- (void)printlnWithChar:(unichar)ch;
- (void)printlnWithDouble:(double)dnum;
- (void)printlnWithFloat:(float)fnum;
- (void)printlnWithInt:(int)inum;
- (void)printlnWithLong:(long long int)lnum;
- (void)printlnWithId:(id)obj;
- (void)printlnWithNSString:(NSString *)str;
- (void)printlnWithBoolean:(BOOL)bool_;
- (void)setError;
- (void)writeWithByteArray:(IOSByteArray *)buffer
                   withInt:(int)offset
                   withInt:(int)length;
- (void)writeWithInt:(int)oneByte;
- (JavaIoPrintStream *)appendWithChar:(unichar)c;
- (JavaIoPrintStream *)appendWithJavaLangCharSequence:(id<JavaLangCharSequence>)csq;
- (JavaIoPrintStream *)appendWithJavaLangCharSequence:(id<JavaLangCharSequence>)csq
                                              withInt:(int)start
                                              withInt:(int)end;
- (void)copyAllFieldsTo:(JavaIoPrintStream *)other;
@end

J2OBJC_FIELD_SETTER(JavaIoPrintStream, encoding_, NSString *)
J2OBJC_FIELD_SETTER(JavaIoPrintStream, lineSeparator_, NSString *)

#endif // _JavaIoPrintStream_H_
