//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: apache_harmony/classlib/modules/luni/src/main/java/java/io/PrintWriter.java
//
//  Created by tball on 9/18/13.
//

#ifndef _JavaIoPrintWriter_H_
#define _JavaIoPrintWriter_H_

@class IOSCharArray;
@class JavaIoFile;
@class JavaIoOutputStream;
@protocol JavaLangCharSequence;

#import "JreEmulation.h"
#include "java/io/Writer.h"

@interface JavaIoPrintWriter : JavaIoWriter {
 @public
  JavaIoWriter *out_;
  BOOL ioError_;
  BOOL autoflush_;
  NSString *lineSeparator_;
}

- (id)initWithJavaIoOutputStream:(JavaIoOutputStream *)outArg;
- (id)initWithJavaIoOutputStream:(JavaIoOutputStream *)outArg
                     withBoolean:(BOOL)autoflush;
- (id)initWithJavaIoWriter:(JavaIoWriter *)wr;
- (id)initWithJavaIoWriter:(JavaIoWriter *)wr
               withBoolean:(BOOL)autoflush;
- (id)initWithJavaIoFile:(JavaIoFile *)file;
- (id)initWithJavaIoFile:(JavaIoFile *)file
            withNSString:(NSString *)csn;
- (id)initWithNSString:(NSString *)fileName;
- (id)initWithNSString:(NSString *)fileName
          withNSString:(NSString *)csn;
- (BOOL)checkError;
- (void)close;
- (void)flush;
- (void)printWithCharArray:(IOSCharArray *)charArray;
- (void)printWithChar:(unichar)ch;
- (void)printWithDouble:(double)dnum;
- (void)printWithFloat:(float)fnum;
- (void)printWithInt:(int)inum;
- (void)printWithLong:(long long int)lnum;
- (void)printWithId:(id)obj;
- (void)printWithNSString:(NSString *)str;
- (void)printWithBoolean:(BOOL)bool_;
- (void)println;
- (void)printlnWithCharArray:(IOSCharArray *)charArray;
- (void)printlnWithChar:(unichar)ch;
- (void)printlnWithDouble:(double)dnum;
- (void)printlnWithFloat:(float)fnum;
- (void)printlnWithInt:(int)inum;
- (void)printlnWithLong:(long long int)lnum;
- (void)printlnWithId:(id)obj;
- (void)printlnWithNSString:(NSString *)str;
- (void)printlnWithBoolean:(BOOL)bool_;
- (void)setError;
- (void)writeWithCharArray:(IOSCharArray *)buf;
- (void)writeWithCharArray:(IOSCharArray *)buf
                   withInt:(int)offset
                   withInt:(int)count;
- (void)writeWithInt:(int)oneChar;
- (void)doWriteWithCharArray:(IOSCharArray *)buf
                     withInt:(int)offset
                     withInt:(int)count;
- (void)writeWithNSString:(NSString *)str;
- (void)writeWithNSString:(NSString *)str
                  withInt:(int)offset
                  withInt:(int)count;
- (JavaIoPrintWriter *)appendWithChar:(unichar)c;
- (JavaIoPrintWriter *)appendWithJavaLangCharSequence:(id<JavaLangCharSequence>)csq;
- (JavaIoPrintWriter *)appendWithJavaLangCharSequence:(id<JavaLangCharSequence>)csq
                                              withInt:(int)start
                                              withInt:(int)end;
- (void)copyAllFieldsTo:(JavaIoPrintWriter *)other;
@end

J2OBJC_FIELD_SETTER(JavaIoPrintWriter, out_, JavaIoWriter *)
J2OBJC_FIELD_SETTER(JavaIoPrintWriter, lineSeparator_, NSString *)

#endif // _JavaIoPrintWriter_H_
