//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/tball/tmp/j2objc-0.8.6.1/junit/build_result/java/junit/runner/Version.java
//
//  Created by tball on 9/18/13.
//

#ifndef _JunitRunnerVersion_H_
#define _JunitRunnerVersion_H_

@class IOSObjectArray;

#import "JreEmulation.h"

@interface JunitRunnerVersion : NSObject {
}

- (id)init;
+ (NSString *)id__;
+ (void)mainWithNSStringArray:(IOSObjectArray *)args;
@end

#endif // _JunitRunnerVersion_H_
