//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/tball/tmp/j2objc-0.8.6.1/junit/build_result/java/org/junit/internal/matchers/TypeSafeMatcher.java
//
//  Created by tball on 9/18/13.
//

#ifndef _OrgJunitInternalMatchersTypeSafeMatcher_H_
#define _OrgJunitInternalMatchersTypeSafeMatcher_H_

@class IOSClass;
@class JavaLangReflectMethod;

#import "JreEmulation.h"
#include "org/hamcrest/BaseMatcher.h"

@interface OrgJunitInternalMatchersTypeSafeMatcher : OrgHamcrestBaseMatcher {
 @public
  IOSClass *expectedType_;
}

- (BOOL)matchesSafelyWithId:(id)item;
- (id)init;
+ (IOSClass *)findExpectedTypeWithIOSClass:(IOSClass *)fromClass;
+ (BOOL)isMatchesSafelyMethodWithJavaLangReflectMethod:(JavaLangReflectMethod *)method;
- (id)initWithIOSClass:(IOSClass *)expectedType;
- (BOOL)matchesWithId:(id)item;
- (void)copyAllFieldsTo:(OrgJunitInternalMatchersTypeSafeMatcher *)other;
@end

J2OBJC_FIELD_SETTER(OrgJunitInternalMatchersTypeSafeMatcher, expectedType_, IOSClass *)

#endif // _OrgJunitInternalMatchersTypeSafeMatcher_H_
