//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/tball/tmp/j2objc-0.8.6.1/junit/build_result/java/org/junit/rules/MethodRule.java
//
//  Created by tball on 9/18/13.
//

#ifndef _OrgJunitRulesMethodRule_H_
#define _OrgJunitRulesMethodRule_H_

@class OrgJunitRunnersModelFrameworkMethod;
@class OrgJunitRunnersModelStatement;

#import "JreEmulation.h"

@protocol OrgJunitRulesMethodRule < NSObject, JavaObject >
- (OrgJunitRunnersModelStatement *)applyWithOrgJunitRunnersModelStatement:(OrgJunitRunnersModelStatement *)base
                                  withOrgJunitRunnersModelFrameworkMethod:(OrgJunitRunnersModelFrameworkMethod *)method
                                                                   withId:(id)target;
@end

#endif // _OrgJunitRulesMethodRule_H_
