//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/tball/tmp/j2objc-0.8.6.1/junit/build_result/java/org/junit/rules/TestRule.java
//
//  Created by tball on 9/18/13.
//

#ifndef _OrgJunitRulesTestRule_H_
#define _OrgJunitRulesTestRule_H_

@class OrgJunitRunnerDescription;
@class OrgJunitRunnersModelStatement;

#import "JreEmulation.h"

@protocol OrgJunitRulesTestRule < NSObject, JavaObject >
- (OrgJunitRunnersModelStatement *)applyWithOrgJunitRunnersModelStatement:(OrgJunitRunnersModelStatement *)base
                                            withOrgJunitRunnerDescription:(OrgJunitRunnerDescription *)description_;
@end

#endif // _OrgJunitRulesTestRule_H_
