//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: apache_harmony/classlib/modules/luni/src/main/java/java/lang/AssertionError.java
//
//  Created by tball on 9/18/13.
//

#ifndef _JavaLangAssertionError_H_
#define _JavaLangAssertionError_H_

#import "JreEmulation.h"
#include "java/lang/Error.h"

#define JavaLangAssertionError_serialVersionUID -5013299493970297370

@interface JavaLangAssertionError : JavaLangError {
}

- (id)init;
- (id)initWithId:(id)detailMessage;
- (id)initWithBoolean:(BOOL)detailMessage;
- (id)initWithChar:(unichar)detailMessage;
- (id)initWithInt:(int)detailMessage;
- (id)initWithLong:(long long int)detailMessage;
- (id)initWithFloat:(float)detailMessage;
- (id)initWithDouble:(double)detailMessage;
@end

#endif // _JavaLangAssertionError_H_
