//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/java/lang/Deprecated.java
//
//  Created by tball on 9/18/13.
//

#ifndef _JavaLangDeprecated_H_
#define _JavaLangDeprecated_H_

#import "JreEmulation.h"
#include "java/lang/annotation/Annotation.h"

@protocol JavaLangDeprecated < JavaLangAnnotationAnnotation >
@end

@interface JavaLangDeprecatedImpl : NSObject < JavaLangDeprecated >
@end

#endif // _JavaLangDeprecated_H_
