//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/java/lang/SafeVarargs.java
//
//  Created by tball on 9/18/13.
//

#ifndef _JavaLangSafeVarargs_H_
#define _JavaLangSafeVarargs_H_

#import "JreEmulation.h"
#include "java/lang/annotation/Annotation.h"

@protocol JavaLangSafeVarargs < JavaLangAnnotationAnnotation >
@end

@interface JavaLangSafeVarargsImpl : NSObject < JavaLangSafeVarargs >
@end

#endif // _JavaLangSafeVarargs_H_
