//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/tball/tmp/j2objc-0.8.6.1/junit/build_result/java/org/junit/After.java
//
//  Created by tball on 9/18/13.
//

#ifndef _OrgJunitAfter_H_
#define _OrgJunitAfter_H_

#import "JreEmulation.h"
#include "java/lang/annotation/Annotation.h"

@protocol OrgJunitAfter < JavaLangAnnotationAnnotation >
@end

@interface OrgJunitAfterImpl : NSObject < OrgJunitAfter >
@end

#endif // _OrgJunitAfter_H_
