//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/tball/tmp/j2objc-0.8.6.1/junit/build_result/java/org/junit/AfterClass.java
//
//  Created by tball on 9/18/13.
//

#ifndef _OrgJunitAfterClass_H_
#define _OrgJunitAfterClass_H_

#import "JreEmulation.h"
#include "java/lang/annotation/Annotation.h"

@protocol OrgJunitAfterClass < JavaLangAnnotationAnnotation >
@end

@interface OrgJunitAfterClassImpl : NSObject < OrgJunitAfterClass >
@end

#endif // _OrgJunitAfterClass_H_
