//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/tball/tmp/j2objc-0.8.6.1/junit/build_result/java/org/junit/BeforeClass.java
//
//  Created by tball on 9/18/13.
//

#ifndef _OrgJunitBeforeClass_H_
#define _OrgJunitBeforeClass_H_

#import "JreEmulation.h"
#include "java/lang/annotation/Annotation.h"

@protocol OrgJunitBeforeClass < JavaLangAnnotationAnnotation >
@end

@interface OrgJunitBeforeClassImpl : NSObject < OrgJunitBeforeClass >
@end

#endif // _OrgJunitBeforeClass_H_
