//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/tball/tmp/j2objc-0.8.6.1/junit/build_result/java/org/junit/Before.java
//
//  Created by tball on 9/18/13.
//

#ifndef _OrgJunitBefore_H_
#define _OrgJunitBefore_H_

#import "JreEmulation.h"
#include "java/lang/annotation/Annotation.h"

@protocol OrgJunitBefore < JavaLangAnnotationAnnotation >
@end

@interface OrgJunitBeforeImpl : NSObject < OrgJunitBefore >
@end

#endif // _OrgJunitBefore_H_
