//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/tball/tmp/j2objc-0.8.6.1/junit/build_result/java/org/junit/ClassRule.java
//
//  Created by tball on 9/18/13.
//

#ifndef _OrgJunitClassRule_H_
#define _OrgJunitClassRule_H_

#import "JreEmulation.h"
#include "java/lang/annotation/Annotation.h"

@protocol OrgJunitClassRule < JavaLangAnnotationAnnotation >
@end

@interface OrgJunitClassRuleImpl : NSObject < OrgJunitClassRule >
@end

#endif // _OrgJunitClassRule_H_
