//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/tball/tmp/j2objc-0.8.6.1/junit/build_result/java/org/junit/Rule.java
//
//  Created by tball on 9/18/13.
//

#ifndef _OrgJunitRule_H_
#define _OrgJunitRule_H_

#import "JreEmulation.h"
#include "java/lang/annotation/Annotation.h"

@protocol OrgJunitRule < JavaLangAnnotationAnnotation >
@end

@interface OrgJunitRuleImpl : NSObject < OrgJunitRule >
@end

#endif // _OrgJunitRule_H_
