//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/tball/tmp/j2objc-0.8.6.1/junit/build_result/java/org/junit/internal/ArrayComparisonFailure.java
//
//  Created by tball on 9/18/13.
//

#ifndef _OrgJunitInternalArrayComparisonFailure_H_
#define _OrgJunitInternalArrayComparisonFailure_H_

@protocol JavaUtilList;

#import "JreEmulation.h"
#include "java/lang/AssertionError.h"

#define OrgJunitInternalArrayComparisonFailure_serialVersionUID 1

@interface OrgJunitInternalArrayComparisonFailure : JavaLangAssertionError {
 @public
  id<JavaUtilList> fIndices_;
  NSString *fMessage_;
  JavaLangAssertionError *fCause_;
}

- (id)initWithNSString:(NSString *)message
withJavaLangAssertionError:(JavaLangAssertionError *)cause
               withInt:(int)index;
- (void)addDimensionWithInt:(int)index;
- (NSString *)getMessage;
- (NSString *)description;
- (void)copyAllFieldsTo:(OrgJunitInternalArrayComparisonFailure *)other;
@end

J2OBJC_FIELD_SETTER(OrgJunitInternalArrayComparisonFailure, fIndices_, id<JavaUtilList>)
J2OBJC_FIELD_SETTER(OrgJunitInternalArrayComparisonFailure, fMessage_, NSString *)
J2OBJC_FIELD_SETTER(OrgJunitInternalArrayComparisonFailure, fCause_, JavaLangAssertionError *)

#endif // _OrgJunitInternalArrayComparisonFailure_H_
