//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/tball/tmp/j2objc-0.8.6.1/junit/build_result/java/org/junit/internal/AssumptionViolatedException.java
//
//  Created by tball on 9/18/13.
//

#ifndef _OrgJunitInternalAssumptionViolatedException_H_
#define _OrgJunitInternalAssumptionViolatedException_H_

@protocol OrgHamcrestDescription;
@protocol OrgHamcrestMatcher;

#import "JreEmulation.h"
#include "java/lang/RuntimeException.h"
#include "org/hamcrest/SelfDescribing.h"

#define OrgJunitInternalAssumptionViolatedException_serialVersionUID 1

@interface OrgJunitInternalAssumptionViolatedException : JavaLangRuntimeException < OrgHamcrestSelfDescribing > {
 @public
  id fValue_;
  id<OrgHamcrestMatcher> fMatcher_;
}

- (id)initWithId:(id)value
withOrgHamcrestMatcher:(id<OrgHamcrestMatcher>)matcher;
- (id)initWithNSString:(NSString *)assumption;
- (NSString *)getMessage;
- (void)describeToWithOrgHamcrestDescription:(id<OrgHamcrestDescription>)description_;
- (void)copyAllFieldsTo:(OrgJunitInternalAssumptionViolatedException *)other;
@end

J2OBJC_FIELD_SETTER(OrgJunitInternalAssumptionViolatedException, fValue_, id)
J2OBJC_FIELD_SETTER(OrgJunitInternalAssumptionViolatedException, fMatcher_, id<OrgHamcrestMatcher>)

#endif // _OrgJunitInternalAssumptionViolatedException_H_
