//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/tball/tmp/j2objc-0.8.6.1/junit/build_result/java/org/junit/internal/ComparisonCriteria.java
//
//  Created by tball on 9/18/13.
//

#ifndef _OrgJunitInternalComparisonCriteria_H_
#define _OrgJunitInternalComparisonCriteria_H_

#import "JreEmulation.h"

@interface OrgJunitInternalComparisonCriteria : NSObject {
}

- (void)arrayEqualsWithNSString:(NSString *)message
                         withId:(id)expecteds
                         withId:(id)actuals;
- (BOOL)isArrayWithId:(id)expected;
- (int)assertArraysAreSameLengthWithId:(id)expecteds
                                withId:(id)actuals
                          withNSString:(NSString *)header;
- (void)assertElementsEqualWithId:(id)expected
                           withId:(id)actual;
- (id)init;
@end

#endif // _OrgJunitInternalComparisonCriteria_H_
