//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/tball/tmp/j2objc-0.8.6.1/junit/build_result/java/org/junit/internal/ExactComparisonCriteria.java
//
//  Created by tball on 9/18/13.
//

#ifndef _OrgJunitInternalExactComparisonCriteria_H_
#define _OrgJunitInternalExactComparisonCriteria_H_

#import "JreEmulation.h"
#include "org/junit/internal/ComparisonCriteria.h"

@interface OrgJunitInternalExactComparisonCriteria : OrgJunitInternalComparisonCriteria {
}

- (void)assertElementsEqualWithId:(id)expected
                           withId:(id)actual;
- (id)init;
@end

#endif // _OrgJunitInternalExactComparisonCriteria_H_
