//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/tball/tmp/j2objc-0.8.6.1/junit/build_result/java/org/junit/internal/InexactComparisonCriteria.java
//
//  Created by tball on 9/18/13.
//

#ifndef _OrgJunitInternalInexactComparisonCriteria_H_
#define _OrgJunitInternalInexactComparisonCriteria_H_

#import "JreEmulation.h"
#include "org/junit/internal/ComparisonCriteria.h"

@interface OrgJunitInternalInexactComparisonCriteria : OrgJunitInternalComparisonCriteria {
 @public
  double fDelta_;
}

- (id)initWithDouble:(double)delta;
- (void)assertElementsEqualWithId:(id)expected
                           withId:(id)actual;
- (void)copyAllFieldsTo:(OrgJunitInternalInexactComparisonCriteria *)other;
@end

#endif // _OrgJunitInternalInexactComparisonCriteria_H_
