//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/tball/tmp/j2objc-0.8.6.1/junit/build_result/java/org/junit/internal/JUnitSystem.java
//
//  Created by tball on 9/18/13.
//

#ifndef _OrgJunitInternalJUnitSystem_H_
#define _OrgJunitInternalJUnitSystem_H_

@class JavaIoPrintStream;

#import "JreEmulation.h"

@protocol OrgJunitInternalJUnitSystem < NSObject, JavaObject >
- (void)exitWithInt:(int)i;
- (JavaIoPrintStream *)out;
@end

#endif // _OrgJunitInternalJUnitSystem_H_
