//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/tball/tmp/j2objc-0.8.6.1/junit/build_result/java/org/junit/internal/TextListener.java
//
//  Created by tball on 9/18/13.
//

#ifndef _OrgJunitInternalTextListener_H_
#define _OrgJunitInternalTextListener_H_

@class JavaIoPrintStream;
@class OrgJunitRunnerDescription;
@class OrgJunitRunnerNotificationFailure;
@class OrgJunitRunnerResult;
@protocol OrgJunitInternalJUnitSystem;

#import "JreEmulation.h"
#include "org/junit/runner/notification/RunListener.h"

@interface OrgJunitInternalTextListener : OrgJunitRunnerNotificationRunListener {
 @public
  JavaIoPrintStream *fWriter_;
}

- (id)initWithOrgJunitInternalJUnitSystem:(id<OrgJunitInternalJUnitSystem>)system;
- (id)initWithJavaIoPrintStream:(JavaIoPrintStream *)writer;
- (void)testRunFinishedWithOrgJunitRunnerResult:(OrgJunitRunnerResult *)result;
- (void)testStartedWithOrgJunitRunnerDescription:(OrgJunitRunnerDescription *)description_;
- (void)testFailureWithOrgJunitRunnerNotificationFailure:(OrgJunitRunnerNotificationFailure *)failure;
- (void)testIgnoredWithOrgJunitRunnerDescription:(OrgJunitRunnerDescription *)description_;
- (JavaIoPrintStream *)getWriter;
- (void)printHeaderWithLong:(long long int)runTime;
- (void)printFailuresWithOrgJunitRunnerResult:(OrgJunitRunnerResult *)result;
- (void)printFailureWithOrgJunitRunnerNotificationFailure:(OrgJunitRunnerNotificationFailure *)each
                                             withNSString:(NSString *)prefix;
- (void)printFooterWithOrgJunitRunnerResult:(OrgJunitRunnerResult *)result;
- (NSString *)elapsedTimeAsStringWithLong:(long long int)runTime;
- (void)copyAllFieldsTo:(OrgJunitInternalTextListener *)other;
@end

J2OBJC_FIELD_SETTER(OrgJunitInternalTextListener, fWriter_, JavaIoPrintStream *)

#endif // _OrgJunitInternalTextListener_H_
