//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/tball/tmp/j2objc-0.8.6.1/junit/build_result/java/org/junit/internal/runners/model/MultipleFailureException.java
//
//  Created by tball on 9/18/13.
//

#ifndef _OrgJunitInternalRunnersModelMultipleFailureException_H_
#define _OrgJunitInternalRunnersModelMultipleFailureException_H_

@protocol JavaUtilList;

#import "JreEmulation.h"
#include "org/junit/runners/model/MultipleFailureException.h"

#define OrgJunitInternalRunnersModelMultipleFailureException_serialVersionUID 1

@interface OrgJunitInternalRunnersModelMultipleFailureException : OrgJunitRunnersModelMultipleFailureException {
}

- (id)initWithJavaUtilList:(id<JavaUtilList>)errors;
@end

#endif // _OrgJunitInternalRunnersModelMultipleFailureException_H_
