//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/tball/tmp/j2objc-0.8.6.1/junit/build_result/java/org/junit/internal/runners/model/ReflectiveCallable.java
//
//  Created by tball on 9/18/13.
//

#ifndef _OrgJunitInternalRunnersModelReflectiveCallable_H_
#define _OrgJunitInternalRunnersModelReflectiveCallable_H_

#import "JreEmulation.h"

@interface OrgJunitInternalRunnersModelReflectiveCallable : NSObject {
}

- (id)run;
- (id)runReflectiveCall;
- (id)init;
@end

#endif // _OrgJunitInternalRunnersModelReflectiveCallable_H_
