//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/tball/tmp/j2objc-0.8.6.1/junit/build_result/java/org/junit/internal/runners/ErrorReportingRunner.java
//
//  Created by tball on 9/18/13.
//

#ifndef _OrgJunitInternalRunnersErrorReportingRunner_H_
#define _OrgJunitInternalRunnersErrorReportingRunner_H_

@class IOSClass;
@class JavaLangThrowable;
@class OrgJunitRunnerDescription;
@class OrgJunitRunnerNotificationRunNotifier;
@protocol JavaUtilList;

#import "JreEmulation.h"
#include "org/junit/runner/Runner.h"

@interface OrgJunitInternalRunnersErrorReportingRunner : OrgJunitRunnerRunner {
 @public
  id<JavaUtilList> fCauses_;
  IOSClass *fTestClass_;
}

- (id)initWithIOSClass:(IOSClass *)testClass
 withJavaLangThrowable:(JavaLangThrowable *)cause;
- (OrgJunitRunnerDescription *)getDescription;
- (void)runWithOrgJunitRunnerNotificationRunNotifier:(OrgJunitRunnerNotificationRunNotifier *)notifier;
- (id<JavaUtilList>)getCausesWithJavaLangThrowable:(JavaLangThrowable *)cause;
- (OrgJunitRunnerDescription *)describeCauseWithJavaLangThrowable:(JavaLangThrowable *)child;
- (void)runCauseWithJavaLangThrowable:(JavaLangThrowable *)child
withOrgJunitRunnerNotificationRunNotifier:(OrgJunitRunnerNotificationRunNotifier *)notifier;
- (void)copyAllFieldsTo:(OrgJunitInternalRunnersErrorReportingRunner *)other;
@end

J2OBJC_FIELD_SETTER(OrgJunitInternalRunnersErrorReportingRunner, fCauses_, id<JavaUtilList>)
J2OBJC_FIELD_SETTER(OrgJunitInternalRunnersErrorReportingRunner, fTestClass_, IOSClass *)

#endif // _OrgJunitInternalRunnersErrorReportingRunner_H_
