//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/tball/tmp/j2objc-0.8.6.1/junit/build_result/java/org/junit/internal/runners/InitializationError.java
//
//  Created by tball on 9/18/13.
//

#ifndef _OrgJunitInternalRunnersInitializationError_H_
#define _OrgJunitInternalRunnersInitializationError_H_

@class IOSObjectArray;
@protocol JavaUtilList;

#import "JreEmulation.h"
#include "java/lang/Exception.h"

#define OrgJunitInternalRunnersInitializationError_serialVersionUID 1

@interface OrgJunitInternalRunnersInitializationError : JavaLangException {
 @public
  id<JavaUtilList> fErrors_;
}

- (id)initWithJavaUtilList:(id<JavaUtilList>)errors;
- (id)initWithJavaLangThrowableArray:(IOSObjectArray *)errors;
- (id)initWithNSString:(NSString *)string;
- (id<JavaUtilList>)getCauses;
- (void)copyAllFieldsTo:(OrgJunitInternalRunnersInitializationError *)other;
@end

J2OBJC_FIELD_SETTER(OrgJunitInternalRunnersInitializationError, fErrors_, id<JavaUtilList>)

#endif // _OrgJunitInternalRunnersInitializationError_H_
