//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/tball/tmp/j2objc-0.8.6.1/junit/build_result/java/org/junit/internal/runners/JUnit38ClassRunner.java
//
//  Created by tball on 9/18/13.
//

#ifndef _OrgJunitInternalRunnersJUnit38ClassRunner_H_
#define _OrgJunitInternalRunnersJUnit38ClassRunner_H_

@class IOSClass;
@class JavaLangThrowable;
@class JunitFrameworkAssertionFailedError;
@class JunitFrameworkTestSuite;
@class OrgJunitRunnerDescription;
@class OrgJunitRunnerManipulationFilter;
@class OrgJunitRunnerManipulationSorter;
@class OrgJunitRunnerNotificationRunNotifier;
@protocol JunitFrameworkTest;

#import "JreEmulation.h"
#include "junit/framework/TestListener.h"
#include "org/junit/runner/Runner.h"
#include "org/junit/runner/manipulation/Filterable.h"
#include "org/junit/runner/manipulation/Sortable.h"

@interface OrgJunitInternalRunnersJUnit38ClassRunner : OrgJunitRunnerRunner < OrgJunitRunnerManipulationFilterable, OrgJunitRunnerManipulationSortable > {
 @public
  id<JunitFrameworkTest> fTest_;
}

- (id)initWithIOSClass:(IOSClass *)klass;
- (id)initWithJunitFrameworkTest:(id<JunitFrameworkTest>)test;
- (void)runWithOrgJunitRunnerNotificationRunNotifier:(OrgJunitRunnerNotificationRunNotifier *)notifier;
- (id<JunitFrameworkTestListener>)createAdaptingListenerWithOrgJunitRunnerNotificationRunNotifier:(OrgJunitRunnerNotificationRunNotifier *)notifier;
- (OrgJunitRunnerDescription *)getDescription;
+ (OrgJunitRunnerDescription *)makeDescriptionWithJunitFrameworkTest:(id<JunitFrameworkTest>)test;
+ (NSString *)createSuiteDescriptionWithJunitFrameworkTestSuite:(JunitFrameworkTestSuite *)ts;
- (void)filterWithOrgJunitRunnerManipulationFilter:(OrgJunitRunnerManipulationFilter *)filter;
- (void)sortWithOrgJunitRunnerManipulationSorter:(OrgJunitRunnerManipulationSorter *)sorter;
- (void)setTestWithJunitFrameworkTest:(id<JunitFrameworkTest>)test;
- (id<JunitFrameworkTest>)getTest;
- (void)copyAllFieldsTo:(OrgJunitInternalRunnersJUnit38ClassRunner *)other;
@end

J2OBJC_FIELD_SETTER(OrgJunitInternalRunnersJUnit38ClassRunner, fTest_, id<JunitFrameworkTest>)

@interface OrgJunitInternalRunnersJUnit38ClassRunner_OldTestClassAdaptingListener : NSObject < JunitFrameworkTestListener > {
 @public
  OrgJunitRunnerNotificationRunNotifier *fNotifier_;
}

- (id)initWithOrgJunitInternalRunnersJUnit38ClassRunner:(OrgJunitInternalRunnersJUnit38ClassRunner *)outer$
              withOrgJunitRunnerNotificationRunNotifier:(OrgJunitRunnerNotificationRunNotifier *)notifier;
- (void)endTestWithJunitFrameworkTest:(id<JunitFrameworkTest>)test;
- (void)startTestWithJunitFrameworkTest:(id<JunitFrameworkTest>)test;
- (void)addErrorWithJunitFrameworkTest:(id<JunitFrameworkTest>)test
                 withJavaLangThrowable:(JavaLangThrowable *)t;
- (OrgJunitRunnerDescription *)asDescriptionWithJunitFrameworkTest:(id<JunitFrameworkTest>)test;
- (IOSClass *)getEffectiveClassWithJunitFrameworkTest:(id<JunitFrameworkTest>)test;
- (NSString *)getNameWithJunitFrameworkTest:(id<JunitFrameworkTest>)test;
- (void)addFailureWithJunitFrameworkTest:(id<JunitFrameworkTest>)test
  withJunitFrameworkAssertionFailedError:(JunitFrameworkAssertionFailedError *)t;
- (void)copyAllFieldsTo:(OrgJunitInternalRunnersJUnit38ClassRunner_OldTestClassAdaptingListener *)other;
@end

J2OBJC_FIELD_SETTER(OrgJunitInternalRunnersJUnit38ClassRunner_OldTestClassAdaptingListener, fNotifier_, OrgJunitRunnerNotificationRunNotifier *)

#endif // _OrgJunitInternalRunnersJUnit38ClassRunner_H_
