//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/tball/tmp/j2objc-0.8.6.1/junit/build_result/java/org/junit/runners/model/RunnerScheduler.java
//
//  Created by tball on 9/18/13.
//

#ifndef _OrgJunitRunnersModelRunnerScheduler_H_
#define _OrgJunitRunnersModelRunnerScheduler_H_

@protocol JavaLangRunnable;

#import "JreEmulation.h"

@protocol OrgJunitRunnersModelRunnerScheduler < NSObject, JavaObject >
- (void)scheduleWithJavaLangRunnable:(id<JavaLangRunnable>)childStatement;
- (void)finished;
@end

#endif // _OrgJunitRunnersModelRunnerScheduler_H_
