//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/tball/tmp/j2objc-0.8.6.1/junit/build_result/java/org/junit/runners/model/Statement.java
//
//  Created by tball on 9/18/13.
//

#ifndef _OrgJunitRunnersModelStatement_H_
#define _OrgJunitRunnersModelStatement_H_

#import "JreEmulation.h"

@interface OrgJunitRunnersModelStatement : NSObject {
}

- (void)evaluate;
- (id)init;
@end

#endif // _OrgJunitRunnersModelStatement_H_
