//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/tball/tmp/j2objc-0.8.6.1/junit/build_result/java/org/junit/internal/requests/ClassRequest.java
//
//  Created by tball on 9/18/13.
//

#ifndef _OrgJunitInternalRequestsClassRequest_H_
#define _OrgJunitInternalRequestsClassRequest_H_

@class IOSClass;
@class OrgJunitRunnerRunner;

#import "JreEmulation.h"
#include "org/junit/runner/Request.h"

@interface OrgJunitInternalRequestsClassRequest : OrgJunitRunnerRequest {
 @public
  IOSClass *fTestClass_;
  BOOL fCanUseSuiteMethod_;
}

- (id)initWithIOSClass:(IOSClass *)testClass
           withBoolean:(BOOL)canUseSuiteMethod;
- (id)initWithIOSClass:(IOSClass *)testClass;
- (OrgJunitRunnerRunner *)getRunner;
- (void)copyAllFieldsTo:(OrgJunitInternalRequestsClassRequest *)other;
@end

J2OBJC_FIELD_SETTER(OrgJunitInternalRequestsClassRequest, fTestClass_, IOSClass *)

#endif // _OrgJunitInternalRequestsClassRequest_H_
