//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/tball/tmp/j2objc-0.8.6.1/junit/build_result/java/org/junit/runner/Describable.java
//
//  Created by tball on 9/18/13.
//

#ifndef _OrgJunitRunnerDescribable_H_
#define _OrgJunitRunnerDescribable_H_

@class OrgJunitRunnerDescription;

#import "JreEmulation.h"

@protocol OrgJunitRunnerDescribable < NSObject, JavaObject >
- (OrgJunitRunnerDescription *)getDescription;
@end

#endif // _OrgJunitRunnerDescribable_H_
