//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/tball/tmp/j2objc-0.8.6.1/junit/build_result/java/org/junit/runner/Runner.java
//
//  Created by tball on 9/18/13.
//

#ifndef _OrgJunitRunnerRunner_H_
#define _OrgJunitRunnerRunner_H_

@class OrgJunitRunnerDescription;
@class OrgJunitRunnerNotificationRunNotifier;

#import "JreEmulation.h"
#include "org/junit/runner/Describable.h"

@interface OrgJunitRunnerRunner : NSObject < OrgJunitRunnerDescribable > {
}

- (OrgJunitRunnerDescription *)getDescription;
- (void)runWithOrgJunitRunnerNotificationRunNotifier:(OrgJunitRunnerNotificationRunNotifier *)notifier;
- (int)testCount;
- (id)init;
@end

#endif // _OrgJunitRunnerRunner_H_
