//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/tball/tmp/j2objc-0.8.6.1/junit/build_result/java/org/junit/runner/RunWith.java
//
//  Created by tball on 9/18/13.
//

#ifndef _OrgJunitRunnerRunWith_H_
#define _OrgJunitRunnerRunWith_H_

@class IOSClass;

#import "JreEmulation.h"
#include "java/lang/annotation/Annotation.h"

@protocol OrgJunitRunnerRunWith < JavaLangAnnotationAnnotation >

@property (readonly) IOSClass *value;

@end

@interface OrgJunitRunnerRunWithImpl : NSObject < OrgJunitRunnerRunWith > {
 @private
  IOSClass *value;
}

- (id)initWithValue:(IOSClass *)value_;

@end

#endif // _OrgJunitRunnerRunWith_H_
